### Data Encoding
Data Encoding is the process of converting categorical data into numerical data. This is necessary because machine learning algorithms typically require numerical input. There are several techniques for encoding categorical data, including:

- Nominal/OHE Encoding
- Label and Ordinal Encoding
- Target Guided Ordinal Encoding
- Binary Encoding

#### Nominal/OHE Encoding
One hot encoding , also known as nominal encoding is technique to represent categorical data as numerical data,whcih is more suitable for machine learning algorithms.In this Technique,each category is represented as binary vector,where each bit corresponds to a unique category.For example,if we have a categorical feature "Color" with three categories:Red,Green and Blue,one hot encoding would represent these categories as follows:

Red:[1,0,0] Green:[0,1,0] Blue:[0,0,1]

#### disadvantages
-1. It is not a good method to handle outliers
-2. It is not a good method to handle skewed data
-3. It is not a good method to handle missing values
-4. It is not a good method to handle categorical data
-5. It is not a good method to handle high cardinality data

In [5]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
##create a simpel data frame
df = pd.DataFrame({"color": ["red", "blue", "green","green", "red", "blue"]})
print(df)

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [5]:
### create an instance of one hot encoder
encoder = OneHotEncoder()

In [7]:
## perform fit and transform
# fit_tansform returns a sparse matrix. To convert it to a dense array, we can use the toarray() method.
# fit_transform means that we are fitting the encoder to the data and then transforming it in one step. This is a common practice when we want to encode the data and use it for machine learning models.

encoded =encoder.fit_transform(df[["color"]]).toarray()

In [8]:
import pandas as pd
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["color"]))

In [9]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [10]:
encoder.transform([["blue"]]).toarray()

c:\Users\bharg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [11]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [2]:
import seaborn as sns
a = sns.load_dataset('tips')

In [3]:
# transforming the above data
a

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
#hwo to transform the above data
# create an instance of one hot encoder
encoder = OneHotEncoder()
encoded_a = encoder.fit_transform(a[["day"]]).toarray()
encoded_a_df = pd.DataFrame(encoded_a, columns=encoder.get_feature_names_out(["day"]))
pd.concat([a, encoded_a_df], axis=1)

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,0.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,0.0,0.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0.0,0.0,0.0,1.0

## Label Encoding
Label encoding  and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable.The labels are usually assigned in alphabetical order or based on the frequency of the categories.For example, if we have a variable "color" with categories "red", "blue", and "green", we can assign the labels as follows:

1. Red :1
2. Green : 2
3. Blue : 3

In [9]:
df = pd.DataFrame({"color": ["red", "blue", "green", "green", "red", "blue"]})

In [10]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lbl_encoder = LabelEncoder()
encoded_lbl= lbl_encoder.fit_transform(df["color"])
encoded_lbl

array([2, 0, 1, 1, 2, 0])

In [14]:
lbl_encoder.transform(["red"])

array([2])

## the problem with label encoding is that it assigns an arbitrary numerical value to each category, which can lead to unintended consequences when used in machine learning models. For example, if we have three categories "red", "blue", and "green", label encoding might assign 0 to "red", 1 to "blue", and 2 to "green". This implies an ordinal relationship between the categories, which may not be the case. In contrast, one-hot encoding creates binary columns for each category, which avoids this issue and allows the model to treat each category independently.

### Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking.That means that the categories have a meaningful order or hierarchy. For example, if we have a feature called "education level" with categories like "high school", "bachelor's degree", "master's degree", and "PhD", we can use label encoding to assign numerical values to these categories based on their order. In this case, we might assign 0 to "high school", 1 to "bachelor's degree", 2 to "master's degree", and 3 to "PhD". This way, the encoded values reflect the ordinal relationship between the categories.
based on its position in the order.For example,if we haev categorical variables "education level " with four possible values("high school", "bachelor's degree", "master's degree", and "PhD"), label encoding would assign the following numerical values:

1.High School
2.College
3.Graduate
4.PhD

Here the ranks are important.

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
df = pd.DataFrame({
    "size":["small","medium","large","medium","small","large"]
})

In [22]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
##create an instance of ordinal encoder
ordinal_encoder = OrdinalEncoder(categories=[["small","medium","large"]])
encoded_ordinal = ordinal_encoder.fit_transform(df[["size"]])

In [26]:
encoded_ordinal

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

## Target Guided Ordinal Encoding

It is a technique used to encode categorical variables into numerical values. This is often necessary because many machine learning algorithms require numerical input.

This encoding technique is useful when we have a categorical variabel with a large number of unique categories and we want to use this variable as a feature in our machine learning model

In Target Guided Ordinal Encoding,we replace each category with a numerical value based on the mean or median of the taregt variable for that category.This creates a monotonic relationship between the categorical variable and the target variable, which can be beneficial for certain machine learning algorithms. This encoding technique is particularly useful when there is a natural order or hierarchy among the categories, and it can help capture the relationship between the categorical variable and the target variable more effectively than other encoding methods.

In [32]:
import pandas as pd
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',"New York"],
    'temperature': [30, 25, 20, 35, 40,60]
})

In [33]:
df

          city  temperature
0     New York           30
1  Los Angeles           25
2      Chicago           20
3      Houston           35
4      Phoenix           40
5     New York           60

In [36]:
mean_temp = df.groupby("city")["temperature"].mean().to_dict()

In [37]:
df['City_encoded'] = df["city"].map(mean_temp)

In [38]:
df

          city  temperature  City_encoded
0     New York           30          45.0
1  Los Angeles           25          25.0
2      Chicago           20          20.0
3      Houston           35          35.0
4      Phoenix           40          40.0
5     New York           60          45.0

In [39]:
df[["city","City_encoded"]]

          city  City_encoded
0     New York          45.0
1  Los Angeles          25.0
2      Chicago          20.0
3      Houston          35.0
4      Phoenix          40.0
5     New York          45.0

In [40]:
import seaborn as sns
b = sns.load_dataset('tips')
b

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

#### the ordinal encoding  for the above one i mean the tips data set
#### so say me why cant we ues ordinal encoding for the day column in the tips data set
because the day column in the tips dataset does not have a natural order. Ordinal encoding is used for categorical variables that have a clear and meaningful order (e.g., small < medium < large). In the case of the day column, there is no inherent ranking or order among the days of the week, so using ordinal encoding would not be appropriate. Instead, one-hot encoding or another suitable encoding method should be used for the day column.
can we useit for size column in the tips data set
but we do have size column in the tips data set and it has a natural order (e.g., small < medium < large). Therefore, we can use ordinal encoding for the size column in the tips dataset, as it allows us to capture the inherent ranking of the sizes.