In [1]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
df = sns.load_dataset('tips')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [7]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [8]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [9]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

## Feature encoding
`Label Encoding`

In [10]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [22]:
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
Y = df['total_bill']

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 42)

In [24]:
X_train

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2
..    ...     ...    ...  ...     ...   ...
106  4.06    Male    Yes  Sat  Dinner     2
14   3.02  Female     No  Sun  Dinner     2
92   1.00  Female    Yes  Fri  Dinner     2
179  3.55    Male    Yes  Sun  Dinner     2
102  2.50  Female    Yes  Sat  Dinner     3

[183 rows x 6 columns]

### Feature Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [27]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [28]:
X_train

      tip  sex  smoker  day  time  size
115  3.50    0       0  Sun     0     2
181  5.65    1       1  Sun     0     2
225  2.50    0       1  Fri     1     2
68   2.01    1       0  Sat     0     2
104  4.08    0       0  Sat     0     2
..    ...  ...     ...  ...   ...   ...
106  4.06    1       1  Sat     0     2
14   3.02    0       0  Sun     0     2
92   1.00    0       1  Fri     0     2
179  3.55    1       1  Sun     0     2
102  2.50    0       1  Sat     0     3

[183 rows x 6 columns]

In [29]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [30]:
X_test

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2
..    ...  ...     ...   ...   ...   ...
172  5.15    1       1   Sun     0     2
242  1.75    1       0   Sat     0     2
152  2.74    1       0   Sun     0     3
231  3.00    1       1   Sat     0     3
155  5.14    0       0   Sun     0     5

[61 rows x 6 columns]

In [31]:
###One hot encoding ---column transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [33]:
ct = ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(drop='first'), [3])], remainder='passthrough'
)

In [34]:
ct.fit_transform(X_train)

array([[0., 1., 0., ..., 0., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [0., 0., 0., ..., 1., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 3.]], shape=(183, 8))

In [35]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [36]:
X_test = ct.transform(X_test)

In [37]:
from sklearn.svm import SVR
svr = SVR()

In [38]:
svr.fit(X_train,Y_train)

SVR()

In [39]:
y_pred = svr.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score ,mean_absolute_error
print(r2_score(Y_test,y_pred))
print(mean_absolute_error(Y_test,y_pred))

0.49798620106004743
4.463296539661224